### ISSUE TITLE
Infrastructure as code

### ISSUE THREAD

**Issue by anujbhan** [airavata-courses/spring17-devops#3]
I have pushed the code for api-server, lets do this for all the other projects to, specially the portal.

Please assign urself, if you wish to contribute

**Comment by Ameya05** [comment]
Hey @anujbhan, I was looking at the terraform.tfstate file in s3.
Was wondering how the values related to launch configuration were created?

**Comment by anujbhan** [comment]
The state files are created by terraform, for example:

1. [spring17-api-infra.tf](https://github.com/airavata-courses/spring17-devops/blob/master/infrastructure/api-server/terraform/aws-infra/spring17-api-infra.tf) file contains the definition for all the infrastructure.
2. [variables.tf](https://github.com/airavata-courses/spring17-devops/blob/master/infrastructure/api-server/terraform/aws-infra/variables.tf) contains all the variables, which can be changed to scale up or scale down infrastructure (instances)

3. When you change something and do a "terraform plan", it will automatically compute the changes and display the changes which will be effective. Finally when you do a "terraform apply" those changes will be pushed to cloud.
